server:
  port: 7002


eureka:
  instance:
    hostname: eureka7002.com   #eureka服务端的实例名称
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己
    fetch-registry: false   #false表示自己端就是注册中心
    service-url:
      defultZone: http://eureka7001.com:7001/eureka/
      #defaultZone: http://eureka7001.com:7001/eureka/   #单机
  #      defaultZone: http://eureka7002.com:7002/eureka/  #集群
spring:
  application:
    name: cloud-eureka-server7002
