server:
  port: 80
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

#配置feign客服端超时时间
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
logging:
  level:
    #feign日志以什么级别监控那个接口
    com.atguigu.springcloud.service.FeignService: debug
spring:
  application:
    name: hystrix-consumer-order

feign:
  hystrix:
    enabled: true
